site_name: Real-time inventory demonstration
site_description: A demonstration of an even-driven architecture based solution with Kafka
repo_url: https://github.com/jbcodeforce/eda-rt-inventory
docs_dir: docs
site_dir: public
edit_uri: edit/main/docs
copyright: Copyright &copy; 2018 - 2024 Jerome Boyer
theme: 
  name: material
  logo: images/logo.drawio.png
  favicon: images/logo.drawio.png
  palette:
    scheme: default
    # primary: blue
  language: en
  features:
      - content.code.annotate
      - content.code.copy
      - content.tooltips
      - search.highlight
      - navigation.instant
      - navigation.instant.progress
      - navigation.tabs
      - navigation.instant
      - navigation.tabs.sticky
      - navigation.tracking
      # - navigation.sections
      # - navigation.expand
      - navigation.footer
      - navigation.tabs.sticky
      - navigation.top
extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/jbcodeforce'
    - icon: fontawesome/brands/linkedin
      link: 'https://linkedin.com/in/jeromeboyer'
    - icon: fontawesome/solid/paper-plane
      mailto: jerome@intelligent-automations.com
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - mermaid2
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - tables
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details

  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Introduction: index.md
  - Design: design.md
  - Demonstration: demo.md
  - Installation: install.md